### ISSUE TITLE
9월 30일 이후 맞춤법 검사 기능이 제거됩니다

### ISSUE THREAD

**Issue by rycont** [hjh010501/neis-counter#27]
지금까지 부산대학교 & 나라인포테크의 한국어 맞춤법 검사기 사이트를 크롤링하여 맞춤법 검사를 제공하였습니다. 9월 30일 이후로 나라인포테크 맞춤법 검사기 사이트에 크롤링 방지 기술이 적용됨에 따라, 맞춤법 검사 기능이 작동하지 않을 예정입니다.

@hjh010501 맞춤법 검사 관련한 코드를 제거하는 PR을 올려두겠습니다 :) 적당한 일시에 머지 해주시면 감사하겠습니다.

---

다음은 맞춤법 검사기 홈페이지에 올라온 공지사항의 전문입니다:

> <알리는 글>
> 한국어 맞춤법/문법 검사기 홈페이지 서버를 새로 구축하였습니다.
> 기존에 한국어 맞춤법/문법 검사기 주소를 2개로 관리했으나, 새 서버에서는 충분히 전체 트래픽을 감당할 수 있기 때문에 일원화하고자 합니다.
> 따라서 현재 주소(speller.cs.pusan.ac.kr)로는 24년 9월 30일까지만 접속하실 수 있으니, 앞으로는 아래의 주소를 이용해 주시길 바랍니다.
> 새 주소: [nara-speller.co.kr](https://nara-speller.co.kr/)
> 더욱 안정적인 서비스 유지 관리를 위한 조치이니 양해를 부탁드립니다.
> 감사합니다.

**Comment by hjh010501** [comment]
챙겨주셔서 감사합니다 @rycont 님 ㅎㅎ :) 9월 30일 이전에 올려주신 PR 머지할 수 있도록 하겠습니다!

**Comment by hjh010501** [comment]
아 근데.. 더 나은 유저 경험을 위해 API 형태로 제공받을 수는 없는지 문의는 해보도록 하겠습니다

**Comment by hjh010501** [comment]
아직 문의 답변은 안와서, 머지는 진행해 두겠습니다 🙏
