### ISSUE TITLE
안녕하세요. LICENSE 파일을 봤지만 저작권에 대한 지식이 부족해서 문의드립니다. 

### ISSUE THREAD

**Issue by coboooo** [hjh010501/neis-counter#8]
안녕하세요. 
LICENSE 파일을 봤지만 저작권에 대한 지식이 부족해서 문의드립니다. 
저는 초보 코더입니다. 
혹시 이 소스를 수정해서 제 사이트에서 사용해도 될지 궁금해서 글을 남깁니다.

**Comment by hjh010501** [comment]
안녕하세요. MIT 라이센스이기에 출처 표기 후 사용하시면 됩니다.
감사합니다.
