### ISSUE TITLE
스크롤바가 표시되지 않는 것 같습니다.

### ISSUE THREAD

**Issue by hyunbin-yu** [hjh010501/neis-counter#9]
![image](https://user-images.githubusercontent.com/27762073/185005048-a14ce6f9-4a97-4453-b5a4-fd12ea5c21b3.png)

텍스트가 15줄을 넘어가면 스크롤바가 표시되지 않는 문제가 있는 것 같습니다

**Comment by hjh010501** [comment]
해결하였습니다. 제보해 주셔서 감사합니다.
